all:
	./generate.sh bash > generated/fpm.bash
	./generate.sh fish > generated/fpm.fish
	./generate.sh zsh  > generated/fpm.zsh

install:
	./generate.sh bash -i
	./generate.sh fish -i
	./generate.sh zsh -i
